-- Seed the shared NFL team reference table (identity + colors only; no logos).
insert into teams (id, name, location, nickname, abbr, conference, division, primary_color, secondary_color, accent_color) values
  ('BUF','Buffalo Bills','Buffalo','Bills','BUF','AFC','East','#00338D','#C60C30','#FFFFFF'),
  ('MIA','Miami Dolphins','Miami','Dolphins','MIA','AFC','East','#008E97','#FC4C02','#FFFFFF'),
  ('NE','New England Patriots','New England','Patriots','NE','AFC','East','#002244','#C60C30','#B0B7BC'),
  ('NYJ','New York Jets','New York','Jets','NYJ','AFC','East','#115740','#F7F7F7','#B0B7BC'),
  ('BAL','Baltimore Ravens','Baltimore','Ravens','BAL','AFC','North','#241773','#9E7C0C','#C8102E'),
  ('CIN','Cincinnati Bengals','Cincinnati','Bengals','CIN','AFC','North','#FB4F14','#FFFFFF','#B0B7BC'),
  ('CLE','Cleveland Browns','Cleveland','Browns','CLE','AFC','North','#4B2E17','#FF3C00','#FFFFFF'),
  ('PIT','Pittsburgh Steelers','Pittsburgh','Steelers','PIT','AFC','North','#101820','#FFB612','#C60C30'),
  ('HOU','Houston Texans','Houston','Texans','HOU','AFC','South','#03202F','#A71930','#FFFFFF'),
  ('IND','Indianapolis Colts','Indianapolis','Colts','IND','AFC','South','#002C5F','#A2AAAD','#FFFFFF'),
  ('JAX','Jacksonville Jaguars','Jacksonville','Jaguars','JAX','AFC','South','#006778','#D7A22A','#FFFFFF'),
  ('TEN','Tennessee Titans','Tennessee','Titans','TEN','AFC','South','#0C2340','#4B92DB','#C8102E'),
  ('DEN','Denver Broncos','Denver','Broncos','DEN','AFC','West','#002244','#FB4F14','#FFFFFF'),
  ('KC','Kansas City Chiefs','Kansas City','Chiefs','KC','AFC','West','#E31837','#FFB81C','#FFFFFF'),
  ('LV','Las Vegas Raiders','Las Vegas','Raiders','LV','AFC','West','#0B0B0B','#A5ACAF','#FFFFFF'),
  ('LAC','Los Angeles Chargers','Los Angeles','Chargers','LAC','AFC','West','#0080C6','#FFC20E','#FFFFFF'),
  ('DAL','Dallas Cowboys','Dallas','Cowboys','DAL','NFC','East','#003594','#869397','#FFFFFF'),
  ('NYG','New York Giants','New York','Giants','NYG','NFC','East','#0B2265','#A71930','#FFFFFF'),
  ('PHI','Philadelphia Eagles','Philadelphia','Eagles','PHI','NFC','East','#004C54','#A5ACAF','#FFFFFF'),
  ('WAS','Washington Commanders','Washington','Commanders','WAS','NFC','East','#5A1414','#FFB612','#FFFFFF'),
  ('CHI','Chicago Bears','Chicago','Bears','CHI','NFC','North','#0B162A','#C83803','#FFFFFF'),
  ('DET','Detroit Lions','Detroit','Lions','DET','NFC','North','#0076B6','#B0B7BC','#FFFFFF'),
  ('GB','Green Bay Packers','Green Bay','Packers','GB','NFC','North','#203731','#FFB612','#FFFFFF'),
  ('MIN','Minnesota Vikings','Minnesota','Vikings','MIN','NFC','North','#4F2683','#FFC62F','#FFFFFF'),
  ('ATL','Atlanta Falcons','Atlanta','Falcons','ATL','NFC','South','#A71930','#A5ACAF','#FFFFFF'),
  ('CAR','Carolina Panthers','Carolina','Panthers','CAR','NFC','South','#0085CA','#BFC0BF','#FFFFFF'),
  ('NO','New Orleans Saints','New Orleans','Saints','NO','NFC','South','#101820','#D3BC8D','#FFFFFF'),
  ('TB','Tampa Bay Buccaneers','Tampa Bay','Buccaneers','TB','NFC','South','#D50A0A','#FF7900','#B1BABF'),
  ('ARI','Arizona Cardinals','Arizona','Cardinals','ARI','NFC','West','#97233F','#FFB612','#FFFFFF'),
  ('LAR','Los Angeles Rams','Los Angeles','Rams','LAR','NFC','West','#003594','#FFD100','#FFFFFF'),
  ('SF','San Francisco 49ers','San Francisco','49ers','SF','NFC','West','#AA0000','#B3995D','#FFFFFF'),
  ('SEA','Seattle Seahawks','Seattle','Seahawks','SEA','NFC','West','#002244','#69BE28','#A5ACAF')
on conflict (id) do update set
  name = excluded.name, location = excluded.location, nickname = excluded.nickname,
  abbr = excluded.abbr, conference = excluded.conference, division = excluded.division,
  primary_color = excluded.primary_color, secondary_color = excluded.secondary_color,
  accent_color = excluded.accent_color;
